In [2]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
#1count how many number of posts are paid and unpaid?
# load the data using pandas
df = pd.read_csv('datasets/fb.csv')
print('fb dataset\n',df)

fb dataset
      Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
..                ...     ...       ...         ...           ...        ...
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
1     0.0                      10460                            19057
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
..    ...                        ...                              ...
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   NaN                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
..                      ...                      ...
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
..                          ...
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
..                                                 ...
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
..                                                ...
495                                              2876
496                                              2104
497                                              2388
498                                              2452
499                                              2200

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
1                                                 1108
2                                                  132
3                                                 1386
4                                                  396
..                                                 ...
495                                                392
496                                                301
497                                                363
498                                                370
499                                                316

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
1          5   130.0   29.0                 164
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
..       ...     ...    ...                 ...
495        5    53.0   26.0                  84
496        0    53.0   22.0                  75
497        4    93.0   18.0                 115
498        7    91.0   38.0                 136
499        0    91.0   28.0                 119

[500 rows x 19 columns]

In [4]:
# label based slicing
paid= df[df['Paid']==1]

In [5]:
row, col=paid.shape
paidrows = row

In [6]:
unpaid= df[df['Paid']==0]

In [7]:
row, col=unpaid.shape
unpaidrows = row

In [8]:
total = paidrows+unpaidrows
print('Total paid and unpaid posts are: \n',total)

Total paid and unpaid posts are:
 499

In [10]:
cric_list = df.loc[:, ['Page total likes', 'Type','Post Month', 'like','comment', 'share',]]

In [12]:
print('Given columns:\n', cric_list)

Given columns:
      Page total likes    Type  Post Month    like  comment  share
0              139441   Photo          12    79.0        4   17.0
1              139441  Status          12   130.0        5   29.0
2              139441   Photo          12    66.0        0   14.0
3              139441   Photo          12  1572.0       58  147.0
4              139441   Photo          12   325.0       19   49.0
..                ...     ...         ...     ...      ...    ...
495             85093   Photo           1    53.0        5   26.0
496             81370   Photo           1    53.0        0   22.0
497             81370   Photo           1    93.0        4   18.0
498             81370   Photo           1    91.0        7   38.0
499             81370   Photo           1    91.0        0   28.0

[500 rows x 6 columns]

In [13]:
info_fifth_m = df['Post Month']
sep_month = df[info_fifth_m==9]
print('Selecting DataSet \n', sep_month)

Selecting DataSet
      Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
155            135700   Photo         2           9             3          7
156            135700   Photo         2           9             2         11
157            135700   Photo         3           9             2          2
158            135700   Photo         2           9             1         10
159            135617   Photo         2           9             1          3
160            135617   Photo         3           9             7          9
161            135617   Photo         2           9             7          3
162            135617   Photo         3           9             6         10
163            135617  Status         2           9             6          4
164            135428   Photo         1           9             5         10
165            135428   Photo         2           9             5          3
166            135428   Photo         1           9             4         10
167            135428   Photo         3           9             4          2
168            135428   Photo         1           9             3         10
169            135428   Photo         2           9             3          2
170            135195   Photo         3           9             2          9
171            135195   Photo         1           9             2          2
172            135195  Status         2           9             1         10
173            135195   Photo         1           9             1          4
174            135195   Photo         2           9             7          3
175            135195  Status         2           9             6         10
176            135195   Photo         3           9             6          3
177            135195   Photo         1           9             5         11
178            135195   Photo         2           9             5          2
179            135195   Photo         2           9             4         10
180            134879  Status         2           9             4          4
181            134879   Photo         1           9             3         10
182            134879   Photo         3           9             3          2
183            134879   Video         1           9             2         10
184            134879   Photo         2           9             2          3
185            134879   Photo         1           9             1         10
186            134879   Photo         2           9             1          6
187            134879   Photo         2           9             7         10
188            134879   Photo         3           9             7          4
189            133679   Photo         2           9             2         10
190            133679   Photo         3           9             2          3

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
155   0.0                       1685                             2999
156   0.0                       3756                             7094
157   0.0                       2656                             4862
158   0.0                       5086                             9493
159   1.0                       2055                             3915
160   0.0                       9384                            14948
161   0.0                       3992                             7255
162   0.0                       7512                            13633
163   0.0                      11096                            21080
164   0.0                       1060                             2004
165   1.0                       2790                             4879
166   1.0                      13856                            37716
167   1.0                      10748                            19724
168   0.0                      41984                            68290
169   1.0                       2522                             4583
170   0.0                       4480                             8039
171   0.0                       1543                             2874
172   0.0                      21256                            41906
173   0.0                       4484                             7829
174   0.0                       4398                             8105
175   1.0                      13216                            24738
176   1.0                      22304                            37159
177   0.0                       6208                            10830
178   0.0                       4518                             8533
179   0.0                       3582                             6518
180   1.0                       9124                            17776
181   0.0                      14152                            38806
182   1.0                       4260                             7989
183   0.0                      30624                            56950
184   0.0                       2363                             4223
185   0.0                       2232                             4005
186   0.0                       4048                             7217
187   0.0                       1804                             2968
188   1.0                       2351                             4028
189   0.0                       3100                             5388
190   1.0                       2360                             4004

     Lifetime Engaged Users  Lifetime Post Consumers  \
155                     322                      295
156                     469                      408
157                     390                      309
158                     622                      509
159                     346                      288
160                     757                      452
161                     598                      447
162                     769                      614
163                    1843                     1724
164                     266                      251
165                     435                      360
166                     519                      450
167                     892                      498
168                    3370                     2420
169                     455                      390
170                     572                      430
171                     360                      334
172                    4840                     4754
173                     545                      424
174                     584                      446
175                    2675                     2584
176                    1805                      984
177                     644                      473
178                     626                      482
179                     537                      430
180                    1476                     1397
181                     631                      549
182                     588                      435
183                    2080                     1956
184                     393                      348
185                     374                      335
186                     544                      405
187                     330                      280
188                     371                      298
189                     518                      422
190                     436                      365

     Lifetime Post Consumptions  \
155                         424
156                         613
157                         445
158                         757
159                         412
160                         652
161                         688
162                         951
163                        2106
164                         337
165                         513
166                         672
167                         719
168                        4074
169                         547
170                         599
171                         463
172                        5906
173                         629
174                         669
175                        2969
176                        1618
177                         678
178                         729
179                         597
180                        1797
181                         836
182                         622
183                        3253
184                         476
185                         458
186                         602
187                         352
188                         392
189                         609
190                         486

     Lifetime Post Impressions by people who have liked your Page  \
155                                               1794
156                                               4935
157                                               3273
158                                               6200
159                                               2970
160                                              11148
161                                               4428
162                                               5503
163                                              16095
164                                               1705
165                                               3501
166                                              26832
167                                              13674
168                                              34802
169                                               3031
170                                               5014
171                                               2373
172                                              35455
173                                               4208
174                                               4799
175                                              19599
176                                              22864
177                                               6866
178                                               4215
179                                               3857
180                                              13887
181                                              19409
182                                               4578
183                                              32033
184                                               3332
185                                               3247
186                                               4046
187                                               2293
188                                               3112
189                                               3927
190                                               2757

     Lifetime Post reach by people who like your Page  \
155                                               953
156                                              2556
157                                              1722
158                                              3298
159                                              1507
160                                              7020
161                                              2420
162                                              3260
163                                              8120
164                                               870
165                                              1999
166                                              9064
167                                              7624
168                                             20928
169                                              1674
170                                              2704
171                                              1228
172                                             17592
173                                              2412
174                                              2616
175                                             10232
176                                             13304
177                                              4016
178                                              2254
179                                              2124
180                                              7092
181                                              6632
182                                              2432
183                                             15744
184                                              1788
185                                              1740
186                                              2280
187                                              1354
188                                              1791
189                                              2274
190                                              1603

     Lifetime People who have liked your Page and engaged with your post  \
155                                                237
156                                                365
157                                                309
158                                                489
159                                                277
160                                                604
161                                                435
162                                                530
163                                               1604
164                                                204
165                                                351
166                                                389
167                                                704
168                                               2126
169                                                333
170                                                416
171                                                267
172                                               4318
173                                                382
174                                                431
175                                               2342
176                                               1349
177                                                495
178                                                439
179                                                404
180                                               1331
181                                                404
182                                                436
183                                               1376
184                                                297
185                                                278
186                                                368
187                                                234
188                                                288
189                                                367
190                                                300

     comment    like  share  Total Interactions
155        0    54.0   16.0                  70
156       16   117.0   30.0                 163
157        1   115.0   21.0                 137
158       30   187.0   35.0                 252
159        1    84.0   13.0                  98
160        6   363.0   40.0                 409
161        6   244.0   32.0                 282
162       22   290.0   98.0                 410
163        4   243.0   41.0                 288
164        0    18.0    NaN                  18
165        0   113.0   19.0                 132
166        2    77.0    5.0                  84
167        8   485.0   64.0                 557
168      144  1622.0  208.0                1974
169        6    99.0   16.0                 121
170        3   188.0   26.0                 217
171        2    30.0    6.0                  38
172       38   163.0   27.0                 228
173        6   179.0   40.0                 225
174        5   204.0   34.0                 243
175        2   165.0   22.0                 189
176       29  1047.0   98.0                1174
177        2   234.0   40.0                 276
178        7   250.0   42.0                 299
179        4   154.0   36.0                 194
180       20   150.0   29.0                 199
181        4   102.0    8.0                 114
182        1   226.0   44.0                 271
183        6   345.0  121.0                 472
184       11    68.0   11.0                  90
185        0    62.0   10.0                  72
186        5   223.0   35.0                 263
187        0    61.0    6.0                  67
188        1   104.0   12.0                 117
189        3   146.0   15.0                 164
190        2   102.0   15.0                 119

In [15]:
sep_list = sep_month.loc[:, ['Post Month', 'Post Weekday','Post Weekday']]
sep_list.mean()

Post Month      9.000000
Post Weekday    3.666667
Post Weekday    3.666667
dtype: float64